version: '3'
services:
  eureka-service:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: ${REPLICA_NUM}
    image: 'amitkshirsagar13/excel-eureka-service'
    labels:
      - 'service=eureka-service'
    ports:
      - '8761:8761'
    environment:
      - ENV=dev
    networks:
      - springcluster
networks:
  springcluster:
    external: false