---
apiVersion: v1
kind: Namespace
metadata:
  name: excel
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
  namespace: excel
data:
  VCONFIGCONTEXTPATH: config
  VEUREKACONTEXTPATH: registry
  VADMINPATH: admin
  VREGION: default
  VEUREKAUSER: config
  VEUREKAPASS: config
  VCONFIGUSER: config
  VCONFIGPASS: config
  VEUREKAHOST: eureka-service
  VEUREKAPORT: 80
  VCONFIGHOST: eureka-service
  VCONFIGPORT: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config-service
  namespace: excel
data:
  VDOMAIN: k8scluster.io
  VPROFILE: excel
  VSERVICENAME: eureka-service
  VCONTEXTPATH: /
  VPORT: 80
---
apiVersion: v1
kind: Deployment
metadata:
  name: eureka-service
  namespace: excel
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: eureka-service
        image: amitkshirsagar13/excel-eureka-service
        envFrom:
         - configMapRef:
             name: eureka-config
         - configMapRef:
             name: eureka-config-service
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: eureka-service
  namespace: excel
spec:
  selector:
    app: eureka-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30761
  type: NodePort
---
apiVersion: v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/tls-acme: "true"
  name: eureka-service
  namespace: excel
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: eureka-service.excel.k8m.k8cluster.io
      http:
        paths:
          - backend:
              serviceName: eureka-service
              servicePort: 80
            path: /