---
apiVersion: v1
kind: Namespace
metadata:
  name: excel
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-service
  namespace: excel
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: eureka-service
        image: amitkshirsagar13/excel-eureka-service
        ports:
        - containerPort: 8761
---
kind: Service
apiVersion: v1
metadata:
  name: eureka-service
  namespace: excel
spec:
  selector:
    app: eureka-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30761
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/tls-acme: "true"
  name: eureka-service
  namespace: excel
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: eureka-service.excel.k8m.excel.io
      http:
        paths:
          - backend:
              serviceName: eureka-service
              servicePort: 8761
            path: /