server:
  context-path: ${VCONTEXTPATH:/}
  display-name: ${${spring.application.name}.${spring.profiles.active}.${VDOMAIN:k8scluster.io}:${VHOSTNAME:${HOSTNAME:localhost}}}
  port: ${VPORT:80}
security:
  basic:
    enabled: false
management:
  context-path: /${VADMINPATH:admin}
  security:
    enabled: false

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: false
    region: ${VREGION:default}
    serviceUrl:
      defaultZone: http://${VEUREKAUSER:config}:${VEUREKAPASS:config}@${VEUREKAHOST:localhost}:${VEUREKAPORT:8761}/${VEUREKACONTEXTPATH:registry}/eureka
  instance:
    instanceId: ${spring.application.name}:${server.display-name}:${server.port}
    hostname: ${server.display-name}
    virtual-host-name: ${server.display-name}
    secure-virtual-host-name: ${server.display-name}
    leaseRenewalIntervalInSeconds: 5
    secure-port-enabled: false
    secure-port: ${VSECUREPORT:${server.port}}
    non-secure-port-enabled: true
    non-secure-port: ${VNONSECUREPORT:${server.port}}
    statusPageUrlPath: http://${server.display-name}:${server.port}${server.context-path}${management.context-path}/info
    healthCheckUrlPath: http://${server.display-name}:${server.port}${server.context-path}${management.context-path}/health    
    home-page-url: http://${server.display-name}:${server.port}${server.context-path}
    status-page-url: http://${server.display-name}:${server.port}${server.context-path}${management.context-path}/info

    
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
    
logging:
  level:
    ROOT: INFO
    org.springframework.web: WARN
    
spring:
  cloud:
    config:
      discovery:
        enabled: true
  user:
    roles: ACTUATOR

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
      circuitBreaker:
        requestVolumeThreshold: 4
        errorThresholdPercentage: 50
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
          numBuckets: 10
  threadpool:
    default:
      coreSize: 4
      maxQueueSize: 8
      queueSizeRejectionThreshold: 5
