spring:
  application:
    name: zuul-gateway

server:
  port: ${VPORT:6050}
  ssl:
    enabled: false
    key-store: classpath:keystore.jks
    key-store-password: password
    key-alias: tomcat

security:
  basic:
    enabled: false
management:
  context-path: /admin
  security:
    enabled: false
eureka:
  client:
    fetchRegistry: false
    preferIpAddress: true
    healthcheck:
      enabled: false
    enabled: false
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: zuul-gateway
    virtual-host-name: zuul-gateway
    secure-port-enabled: false
    non-secure-port-enabled: true
    leaseRenewalIntervalInSeconds: 5
    nonSecurePort: ${VPORT:6050}
    statusPageUrlPath: http://zuul-gateway.excel.k8m.excel.io:${VPORT:6050}/info
    status-page-url: http://zuul-gateway.excel.k8m.excel.io:${VPORT:6050}/info
    healthCheckUrlPath: http://zuul-gateway:${VPORT:6050}/health
    homePageUrl: https://zuul-gateway:${VPORT:6050}/
    home-page-url: https://zuul-gateway:${VPORT:6050}/

zuul:
  routes:
    ovpn_servers:
      path: /**
      serviceId: ovpn_servers
      
ovpn_servers:
  ribbon:
    ServerListRefreshInterval: 15000
    listOfServers: 23.96.48.184:6055,23.100.27.232:6055

ribbon:
  eureka:
    enabled: false  