version: '3'
services:
  sample-service:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    image: 'amitkshirsagar13/excel-sample-service'
    labels:
      - 'service=sample-service'
    ports:
      - '5080:5080'
    environment:
      - ENV=dev
    networks:
      - springcluster
networks:
  springcluster:
    external: false