---
apiVersion: v1
kind: Namespace
metadata:
  name: kong
---
kind: Service
apiVersion: v1
metadata:
  name: kong-service
  namespace: kong
spec:
  selector:
    app: kong-app
  ports:
    - name: port8000
      protocol: TCP
      port: 31800
      targetPort: 8000
    - name: port8001
      protocol: TCP
      port: 31801
      targetPort: 8001
    - name: port8002
      protocol: TCP
      port: 31802
      targetPort: 8002
    - name: port8003
      protocol: TCP
      port: 31803
      targetPort: 8003
    - name: port8004
      protocol: TCP
      port: 31804
      targetPort: 8004
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-env
  namespace: kong
data:
  KONG_LOG_LEVEL: notice
  KONG_DATABASE: cassandra
  KONG_CASSANDRA_CONTACT_POINTS: 168.61.55.8,52.162.212.69
  KONG_CASSANDRA_KEYSPACE: sample_kong
  KONG_CASSANDRA_CONSISTENCY: ONE
  KONG_CASSANDRA_LB_POLICY: DCAwareRoundRobin
  KONG_CASSANDRA_LOCAL_DATACENTER: EUS:1,NCUS:1
  KONG_DB_UPDATE_PROPAGATION: '5'
  KONG_PROXY_ACCESS_LOG: /dev/stdout
  KONG_ADMIN_ACCESS_LOG: /dev/stdout
  KONG_PROXY_ERROR_LOG: /dev/stderr
  KONG_ADMIN_ERROR_LOG: /dev/stderr
  KONG_VITALS: 'on'
  KONG_ADMIN_LISTEN: 0.0.0.0:8001
  KONG_LICENSE_DATA: '{"license":{"signature":"24dd81953adad3a69f067c1ae0f2f8cc34134d15c5ab7f43a0136261d63f6293873ac1ea0885615d76f6fb745ab50efbdde1fb815ad380d1ccbc7bdf5
aa8ce9e","payload":{"customer":"Mastercard","license_creation_date":"2018-09-11","product_subscription":"Kong Enterprise Edition","admin_seats":"5","support_plan":"None","l
icense_expiration_date":"2018-10-11","license_key":"00Q4100000wJ4diEAC_a1V41000006MdgFEAS"},"version":1}}'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-deployment
  namespace: kong
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kong-app
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
      - name: init-kong
        image: kong-ee:latest
        envFrom:
        - configMapRef:
            name: kong-env
        command: ['sh', '-c', 'migrations up']
      containers:
      - name: kong
        image: kong-ee:latest
        envFrom:
        - configMapRef:
            name: kong-env
        ports:
        - name: port8000
          containerPort: 8000
        - name: port8443
          containerPort: 8443
        - name: port8001
          containerPort: 8001
        - name: port8444
          containerPort: 8444
        - name: port8002
          containerPort: 8002
        - name: port8445
          containerPort: 8445
        - name: port8003
          containerPort: 8003
        - name: port8004
          containerPort: 8004